tensorboard: True
random_seed: 48

model_name: decapoda-research/llama-7b-hf # EleutherAI/gpt-j-6B gpt2
target_model: /mnt/data0/fuwenjie/MIA-LLMs/ft_llms/llama/wiki103/target/checkpoint-3000 # valid model:
reference_model: /mnt/data0/fuwenjie/MIA-LLMs/ft_llms/llama/wiki103/refer/checkpoint-400 #
dataset_name: wikitext # xsum, ag_news, wikitext
dataset_config_name: wikitext-103-raw-v1 # wikitext-2-raw-v1 null
cache_path: ./cache
use_dataset_cache: true
packing: true
add_eos_token: false
add_bos_token: false
pad_token_id: null
attack_kind: stat # valid attacks: nn, stat
eval_batch_size: 1 # batch size of the evaluation phase
maximum_samples: 200 # the maximum samples number for member and non-member records.
block_size: 128
validation_split_percentage: 0.1
preprocessing_num_workers: 1
mask_filling_model_name: t5-base
buffer_size: 1 # TODO: figure out how this parameter works.
mask_top_p: 1.0
span_length: 2
pct: 0.3 # pct_words_masked
ceil_pct: false
int8: false
half: false
perturbation_number: 1 # the number of different perturbation strength / position
sample_number: 10 # the number of samples for each data group

train_sta_idx: 0
train_end_idx: 10000
eval_sta_idx: 0
eval_end_idx: 1000

loss_kind: ddpm # valid loss estimation methods: ddpm, ddim
time_step: 10
time_sec: 100
calibration: true # whether to enable calibration


diffusion_sample_number: 10 # the number of equidistant sampling
diffusion_sample_steps: [0, 50, 100, 150, 200, 250, 300, 350, 400, 450] # the sample steps of diffusion model

extensive_per_num: 10 # sample number, should be set 1 for diffusion models
start_strength: 0.95 # start strength factor of the perturbation mechanism
end_strength: 0.7 # end strength factor of the perturbation mechanism
attack_data_path: attack
#
epoch_number: 110
load_trained: false # whether to load existing trained attack model
load_attack_data: true # whether to load prepared attack data if existing.
split: [123123, 3213]